### ISSUE TITLE
Vrome hint don't work properly on pages with many links

### ISSUE THREAD

**Issue by ReneFroger** [jinzhu/vrome#313]
For example, I use hints on pages with more than 30 links. 

3 links have the keys GJK, GJ, GJL

When I want to select the link with the hint GJ, then he is waiting on the latest letter (K or L). When I press Enter, nothing happened. This problem is not always reproducable, on some pages I get this issue, on some pages I don't get this issue. 

How can be this solved?

**Comment by szborows** [comment]
@jinzhu I think this should be emphasized in docs. Lost about half of an hour to find this ticket. (https://github.com/jinzhu/vrome/blob/master/Features.mkd)
