### ISSUE TITLE
cntrl-u and cntrl-d do not work as expected compared to Vim or Vimperator

### ISSUE THREAD

**Issue by hammerandtongs** [jinzhu/vrome#332]
These should be doing 

Ctrl+d - move Down half a page
Ctrl+u - move Up half a page

These are some of my most used keys in any Vim binding I use.

**Comment by johnbeard** [comment]
@hammerandtongs: What are they doing for you? Both these keys work for me as described.

**Comment by hammerandtongs** [comment]
If these keys are correct now(and probably should be documented as such) I'm using cvim these days so I can't verify the current state.

If they are doing vim halfpage up/down instead of the old behavior (which sadly I didn't include in the old report) the bug should be closed.

**Comment by simendsjo** [comment]
These has worked previously for me, but have now stopped working. I notice this is a very old issue..
Vrome: 2.19.12
Chromium: 54.0.2840.90

**Comment by simendsjo** [comment]
Also, Ctrl-L activates the previously active tab.

**Comment by jinzhu** [comment]
@simendsjo seems all works for me, maybe you have some other plugins installed changed the behaviour ?

**Comment by simendsjo** [comment]
I have tried disabling all other plugins and both chrome and chromium. Not sure what else I can test.
