### ISSUE TITLE
unmap <C-f> doesn't work in mac OSX

### ISSUE THREAD

**Issue by kymtwyf** [jinzhu/vrome#338]
when press Command+F, still the *Hint {multi mode}* goes first. I need to press twice Command+F in order to search in page

**Comment by lehmacdj** [comment]
<C-f> represents control F so it shouldn't work.  I think that the host key is usually D (i.e. <D-f>), but I can't seem to get this to work either.  Looking for a solution to this problem too.

**Comment by jinzhu** [comment]
`unmap <M-f>` in your options

**Comment by lehmacdj** [comment]
Thanks.
