### ISSUE TITLE
Key Bindings / Temporary turn off - Maybe a Noob request..

### ISSUE THREAD

**Issue by ichbinskyr** [jinzhu/vrome#343]
I'm new to using Vrome, and I'm using it on a work computer to make a certain website that is mouse clicking extensive. Using it in a way of clicking f to open the hint menu and clicking corresponding letter to open links on the page so I'm able to navigate the page with the keyboard easily.

I've come to realize ctrl+a for select all and worse ctrl+f which is normally find in page is causing issues with Vrome since they're bound to other options and while ctrl+a moves to front of line paragraph and then selects all if I do the same key combination again I'm expecting it to work the way it should work. Ctrl+F seems to be a hit or miss depending on what page I'm on whether it'll open the find bar or scroll down, which is an issue.

If there were an easy way to change key bindings, without needing to install stuff on the computer itself to further customize it easier to not sit on most used keyboard combinations it would be useful. 

Otherwise, have a way to toggle watching the keystrokes off like Vimperator has as shift+esc (I know in Chrome it will have to be a different combination as shift+esc brings up Chrome's task manager). At least without having to manually go through Chrome's extensions and disabling it when it's least convenient.

**Comment by blackberryoctopus** [comment]
@ichbinskyr It is possible to disable key bindings by pressing ctrl+v which enables "pass through" mode of vrome.
