### ISSUE TITLE
Hint mode searches instead of using letters

### ISSUE THREAD

**Issue by abudden** [jinzhu/vrome#345]
I'm trying to get hint mode working in vrome, but it seems to only work as a search implementation and not using the hints that are presented on the screen.  For example, if I enter hint mode by pressing 'f' or 'F', I get something that looks like this:

![press_f](https://cloud.githubusercontent.com/assets/670607/11039018/a9abd924-86fd-11e5-8c9a-87a97ec112bf.png)

This looks promising: I have lots of hints that have appeared next to the links.  If I decide I want the one near the bottom with the hint "AS", I would expect to press "A", then "S" to open that link.  However, if I press "A", it seems to search for all links with an "A" in the title and re-allocate hints for those links:

![press_a](https://cloud.githubusercontent.com/assets/670607/11039021/af467402-86fd-11e5-8b93-8d4af0fea866.png)

If I then press "S", it searches for all links with "AS" in the title and re-allocates hints for those links:

![press_s](https://cloud.githubusercontent.com/assets/670607/11039025/b16ef31c-86fd-11e5-888b-20d1cb2692c6.png)

So as far as I can tell, the only way to use hint mode is to use the text of the link.  If this is the case (which would be a big shame from my point of view), why does it display hints in the first place?

The documentation also says that it can use letters or numbers for the hints, but I've tried setting useletters=1 and useletters=0 but it seems to make no difference.  I've also tried setting hintkeys=ABCDEFJKLMNOPQRSTUVWXYZ, but that also seems to have no effect on my problem.

My vrome configuration is here: https://bitbucket.org/abudden/config/raw/default/vrome/vromerc.  I've also tried deleting the entire vrome config such that the options page shows it as empty - this made no difference (including after refreshing the page).  I also went into the developer tools on the options window and deleted everything in LocalStorage, but again this made no difference.  The version of vrome installed (from the Chrome store) is 2.9.8.

Any help you can offer would be much appreciated.

**Comment by yang-ling** [comment]
Did you press `a` or `A`(Shift+a)?

Pressing `as` will give you what you want.

**Comment by abudden** [comment]
Ah, thank you.  Yes, that works.  I assumed I had to type the letters as displayed - I would probably find it more intuitive if the capitalisation was for the short sequence of 1 or 2 letters and lowercase was for typing longer strings for a search, but maybe that's just me.  Any chance of an option to display the letters in lowercase to make it more obvious what you have to type?

**Comment by jinzhu** [comment]
lowercase is used for hint, upper case is used for search, I think it is fine once you know the rules, display is as lowercased doesn't looks good ;)
