### ISSUE TITLE
Report Security Issues

### ISSUE THREAD

**Issue by fd0** [jinzhu/vrome#349]
Hi, I was unable to find your process for reporting security vulnerabilities, is that documented somewhere? Who can I report an issue to?

**Comment by fd0** [comment]
Sorry, to bother you again, but I really need to report a critical vulnerability to someone. Any progress on this?

**Comment by jinzhu** [comment]
Hi @fd0 

Could you drop me an email `wosmvp@gmail.com` ?

**Comment by fd0** [comment]
will do, thank you.

**Comment by fd0** [comment]
Did you get my email? Are you able to reproduce the issue?

**Comment by fd0** [comment]
Any news here? Since it's such a grave problem, do you have a plan when this will be fixed? You then also need to inform all users of the problem...

**Comment by jinzhu** [comment]
Thank you for your report.
