### ISSUE TITLE
Doesn't work after upgrade to Chrome 54 in OSX, Linux, Windows

### ISSUE THREAD

**Issue by josephlaw** [jinzhu/vrome#361]
It work in Chrome 53 in OSX, Linux and Windows, but Chrome 54 fail. Server status is in red color.
Inspect views console error:

```
jquery.js:8556 GET http://127.0.0.1:20000/ net::ERR_CONNECTION_REFUSED
chrome_ex_oauth.js:524 Uncaught Error: Fetching request token failed. Status 404(…)
jquery.js:8556 POST http://127.0.0.1:20000/ net::ERR_CONNECTION_REFUSED
```

Any idea to fix it? seem it fail to start local http server on 20000 port, thanks.

**Comment by boris-petrov** [comment]
Hi, I've pushed a fix for the problem - you could either install it from the source or wait for a new version on the Chrome Web Store.

@jinzhu - can you release a new version please?

**Comment by ohmytime** [comment]
@boris-petrov please release a new version that can fix the bug above.
thank you very much!

**Comment by jinzhu** [comment]
@boris-petrov thank you for this, just published a new version.
